apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: microservices
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: main
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-headless
  namespace: microservices
spec:
  clusterIP: None
  selector:
    app: gateway
    version: v1
  ports:
    - port: 8080
      targetPort: 8080