apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment-v1
  namespace: microservices
  labels:
    app: gateway
    version: v1          
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: gateway
      version: v1      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1      
  template:
    metadata:
      labels:
        app: gateway
        version: v1      
        cluster: clustered-app
    spec:
      serviceAccountName: microservice-gateway
      containers:
        - name: gateway
          image: tuantahp/gateway
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.net.preferIPv4Stack=true -Dvertx.jgroups.config=default-configs/default-jgroups-kubernetes.xml -Djgroups.dns.query=clustered-app.microservices.svc.cluster.local -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory  -agentlib:jdwp=transport=dt_socket,server=y,address=5006,suspend=n,quiet=y"
          ports:
            - containerPort: 8080
            - containerPort: 7800
            - containerPort: 5006 # JDWP port
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /readiness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10          