pulsar {
  serviceUrl = "pulsar://localhost:6650"
  adminUrl = "http://localhost:8080"
  topic.in = "wallet.input"
  topic.out = "wallet.result"
}

postgres {
  host = "localhost:5432"
  port = "5432"
  database = "smartconsultor"
  user = "wallet"
  password = "wallet123"
}
